default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todos_api_development

test:
  <<: *default
  database: todos_api_test

production:
  <<: *default
  database: todos_api_production
  username: todos_api
  password: <%= ENV['TODOS_API_DATABASE_PASSWORD'] %>